### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by mrfishie** [mrfishie/node-artemis#14]
The name 'node-artemis' is a bit too generic, and the 'artemis' package [already exists](http://npmjs.org/package/artemis) on NPM. A name that describes this project as a Node-based Artemis server library would be good. This should preferably be done by the time that node-artemis is ready to actually be used. Any ideas?

**Comment by IvanSanchez** [comment]
I would vote for using `asbs`, which is short for **A**rtemis **S**pace **B**ridge **S**imulator. As in `node-asbs-lib`, `node-asbs-proxy`, `node-asbs-server`, `node-asbs-glitter` and so on.

Or we can jokinly refer to it as "asbestos". Just because it sounds similar to "asbs".

**Comment by mrfishie** [comment]
Haha.. I like the idea of 'asbs', but I would like something.. cooler-sounding than `server`.. Perhaps another Greek god like Artemis? Something like Athena, the goddess of war and cunning wisdom (who also built the first ship, supposedly), might work.

**Comment by rjwut** [comment]
I've actually never liked the name "ArtClientLib." I get that the original author didn't want to use "Artemis" in the name because doing so implies an official status where none exists, but "Art" didn't feel like a good substitute. It's also something of a misnomer now, since the library is no longer limited to client-only applications. But the name is so well-established that I hesitate to change it now.

**Comment by rjwut** [comment]
As for these projects, "asbs" seems like a reasonable choice.

**Comment by mrfishie** [comment]
Renamed to node-asbs-server for now. If anyone comes up with something more creative than 'server' let me know!
